# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-09 15:01
from __future__ import unicode_literals

import app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, verbose_name='URL:')),
                ('file', models.FileField(blank=True, upload_to='app/data/temp_docs', validators=[app.validators.validate_file_extension])),
                ('compression_rate', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)])),
                ('remove_lists', models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, max_length=2)),
            ],
        ),
    ]
